app:
 title: "Generative AI BOT"
 subtitle: "Your Friendly Generative AI Restaurant Safety Helper"

palm:
  botname: "the Generative AI created at starbucks"
  context: "Your name is Gen AI BOT. You answer Questions related to restaurant cleanliness and food handling safety."
  temperature: 0.3
  max_output_tokens: 1024
  top_p: 0.6
  top_k: 40
  PROJECT_ID ="qwiklabs-gcp-03-987c5e88d2d4"
  API_KEY ="AIzaSyAyVy43qaTt6ICVRJYdlWEQ0qz7Oltjhnk"
  LOCATION = 'us-central1'
